#!/usr/bin/with-contenv bash
# shellcheck shell=bash

ssh_keys=(/config/ssh_host_*)

if [ ! -e "${ssh_keys[0]}" ]; then
    ssh-keygen -P "" -o -a 100 -t ed25519 -f /config/ssh_host_ed25519_key
    chmod 700 /config/ssh_host_ed25519_key
fi
