on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 8 * * 0"

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at}}
            VCS_REF=${{ github.head_ref }}
          tags: |
            docker.io/guillaumedsde/ssh-ldap:${{ github.sha }}
            docker.io/guillaumedsde/ssh-ldap:latest
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64
            linux/ppc64le
